function info = generateReport(R)
%GENERATEREPORT Write an experiment report as a self-contained HTML file.
%   info = generateReport(R) where R is a struct with (all optional) fields:
%     title, students, rollNumbers, experimentNumber, aim, theory,
%     algorithm (cell), code, parameters, kernel (matrix),
%     images (struct array label/id), metrics (struct array name/value),
%     observations (cell), conclusion, quizScore
%
%   The HTML embeds all images, so it can be opened offline, printed or
%   saved as PDF from any browser ("Print -> Save as PDF"), or opened in
%   Microsoft Word. If MATLAB Report Generator is installed, a .docx
%   version is produced as well.
%
%   info.file / info.name  - the HTML report
%   info.docx              - the Word report ('' if Report Generator is missing)

root = fileparts(fileparts(mfilename('fullpath')));
outDir = fullfile(root, 'reports', 'output');
if ~isfolder(outDir), mkdir(outDir); end

title = get(R, 'title', 'ImageLab Experiment Report');
stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
base = sprintf('%s_%s', regexprep(title, '[^A-Za-z0-9]+', '_'), stamp);
file = fullfile(outDir, [base '.html']);

h = {};
h{end+1} = '<!DOCTYPE html><html><head><meta charset="utf-8">';
h{end+1} = ['<title>' esc(title) '</title><style>'];
h{end+1} = ['body{font-family:Segoe UI,Arial,sans-serif;max-width:900px;margin:30px auto;color:#1b2333;line-height:1.5;padding:0 16px}' ...
    'h1{color:#12305a;border-bottom:3px solid #2e9e5b;padding-bottom:6px}h2{color:#12305a;margin-top:28px}' ...
    'table{border-collapse:collapse;margin:8px 0}td,th{border:1px solid #c9d1de;padding:5px 10px;text-align:left}' ...
    'th{background:#eef2f8}.meta td{border:none;padding:2px 12px 2px 0}pre{background:#f4f6fa;border:1px solid #dde3ec;padding:10px;overflow:auto}' ...
    '.grid{display:flex;flex-wrap:wrap;gap:14px}.fig{width:calc(50% - 7px);text-align:center;font-size:13px}' ...
    '.fig img{max-width:100%;border:1px solid #ccd;image-rendering:pixelated}.kernel td{text-align:center;min-width:42px;font-family:Consolas,monospace}' ...
    '@media print{.fig{break-inside:avoid}}</style></head><body>'];
h{end+1} = ['<h1>' esc(title) '</h1>'];
h{end+1} = '<table class="meta">';
h{end+1} = row('Students', get(R, 'students', ''));
h{end+1} = row('Roll numbers', get(R, 'rollNumbers', ''));
h{end+1} = row('Experiment', num2str(get(R, 'experimentNumber', '')));
h{end+1} = row('Date', char(datetime('now', 'Format', 'dd MMMM yyyy')));
h{end+1} = row('Software', sprintf('MATLAB %s, Image Processing Toolbox: %s', version('-release'), yesno(hasIPT())));
h{end+1} = '</table>';

h = section(h, 'Aim', get(R, 'aim', ''));
h = section(h, 'Theory', get(R, 'theory', ''));

alg = get(R, 'algorithm', {});
if ~isempty(alg)
    h{end+1} = '<h2>Algorithm</h2><ol>';
    for k = 1:numel(alg), h{end+1} = ['<li>' esc(alg{k}) '</li>']; end %#ok<AGROW>
    h{end+1} = '</ol>';
end

code = get(R, 'code', '');
if ~isempty(code)
    h{end+1} = ['<h2>MATLAB Code</h2><pre>' esc(code) '</pre>'];
end

h = section(h, 'Parameters', get(R, 'parameters', ''));

K = get(R, 'kernel', []);
if ~isempty(K) && isnumeric(K)
    h{end+1} = '<h2>Kernel</h2><table class="kernel">';
    for i = 1:size(K, 1)
        cells = arrayfun(@(v) ['<td>' fmt(v) '</td>'], K(i, :), 'UniformOutput', false);
        h{end+1} = ['<tr>' strjoin(cells, '') '</tr>']; %#ok<AGROW>
    end
    h{end+1} = '</table>';
end

imgs = get(R, 'images', []);
if ~isempty(imgs)
    h{end+1} = '<h2>Input and Output</h2><div class="grid">';
    for k = 1:numel(imgs)
        try
            fid = fopen(ilab_store('path', imgs(k).id), 'r');
            data = fread(fid, Inf, '*uint8');
            fclose(fid);
            b64 = matlab.net.base64encode(data);
            h{end+1} = sprintf('<div class="fig"><img src="data:image/png;base64,%s"><br>%s</div>', ...
                b64, esc(imgs(k).label)); %#ok<AGROW>
        catch
            % image no longer available - skip it
        end
    end
    h{end+1} = '</div>';
end

mets = get(R, 'metrics', []);
if ~isempty(mets)
    h{end+1} = '<h2>Metrics</h2><table><tr><th>Measure</th><th>Value</th></tr>';
    for k = 1:numel(mets)
        h{end+1} = sprintf('<tr><td>%s</td><td>%s</td></tr>', esc(mets(k).name), fmt(mets(k).value)); %#ok<AGROW>
    end
    h{end+1} = '</table>';
end

obs = get(R, 'observations', {});
if ~isempty(obs)
    if ischar(obs), obs = {obs}; end
    h{end+1} = '<h2>Observations</h2><ul>';
    for k = 1:numel(obs), h{end+1} = ['<li>' esc(obs{k}) '</li>']; end %#ok<AGROW>
    h{end+1} = '</ul>';
end

h = section(h, 'Result', get(R, 'result', ''));
h = section(h, 'Conclusion', get(R, 'conclusion', ''));
q = get(R, 'quizScore', '');
if ~isempty(q), h = section(h, 'Quiz Score', num2str(q)); end
h{end+1} = '<p style="color:#778;font-size:12px;margin-top:40px">Generated by ImageLab - Interactive Image Processing Laboratory (MATLAB).</p></body></html>';

fid = fopen(file, 'w', 'n', 'UTF-8');
fprintf(fid, '%s\n', h{:});
fclose(fid);

info = struct('file', file, 'name', [base '.html'], 'docx', '');
info.docx = tryDocx(R, outDir, base);
end

% -------------------------------------------------------------------------
function docx = tryDocx(R, outDir, base)
% Optional Word report with MATLAB Report Generator (if installed)
docx = '';
if exist('mlreportgen.dom.Document', 'class') ~= 8, return; end
try
    import mlreportgen.dom.*
    d = Document(fullfile(outDir, base), 'docx');
    append(d, Heading1(get(R, 'title', 'ImageLab Report')));
    for f = {'aim', 'theory', 'parameters', 'conclusion'}
        txt = get(R, f{1}, '');
        if ~isempty(txt)
            append(d, Heading2([upper(f{1}(1)) f{1}(2:end)]));
            append(d, Paragraph(txt));
        end
    end
    imgs = get(R, 'images', []);
    for k = 1:numel(imgs)
        im = Image(ilab_store('path', imgs(k).id));
        im.Width = '3in'; im.Height = '';
        append(d, im);
        append(d, Paragraph(imgs(k).label));
    end
    close(d);
    docx = [base '.docx'];
catch
    docx = '';
end
end

function h = section(h, name, text)
if ~isempty(text)
    h{end+1} = ['<h2>' name '</h2><p>' esc(text) '</p>'];
end
end

function s = row(label, value)
s = ['<tr><td><b>' label '</b></td><td>' esc(value) '</td></tr>'];
end

function v = get(s, name, default)
if isstruct(s) && isfield(s, name) && ~isempty(s.(name)), v = s.(name); else, v = default; end
end

function s = esc(s)
if isnumeric(s), s = num2str(s); end
s = char(s);
s = strrep(s, '&', '&amp;');
s = strrep(s, '<', '&lt;');
s = strrep(s, '>', '&gt;');
s = strrep(s, newline, '<br>');
end

function s = fmt(v)
if ischar(v) || isstring(v), s = esc(v); return; end
if isempty(v), s = '-'; return; end
if ~isfinite(v), s = 'Inf';
elseif v == round(v), s = sprintf('%d', v);
else, s = sprintf('%.4g', v);
end
end

function s = yesno(tf)
if tf, s = 'installed'; else, s = 'not installed (manual implementations used)'; end
end
