import { useEffect, useState } from 'react'
import { useApp } from '../AppContext'
import { asArray, fmt } from '../api'
import { Card, Note, Page, Segmented } from '../components/ui'
import QuizRunner from '../components/QuizRunner'
import GuessFilter from './quiz/GuessFilter'
import PipelineGame from './quiz/PipelineGame'
import ChallengeMode from './quiz/ChallengeMode'

const GAMES = [
  { key: 'rapid', icon: '⚡', title: 'Rapid Fire Quiz', text: '10 questions · 10 seconds each · score, streaks and leaderboard.' },
  { key: 'kernel', icon: '▦', title: 'Kernel Quiz', text: 'A kernel is shown — identify it (Sobel, Laplacian, mean …). Generated by MATLAB.' },
  { key: 'guess', icon: '🔍', title: 'Guess the Filter', text: 'See the original and the processed image — which filter produced it?' },
  { key: 'pipeline', icon: '⛓', title: 'Build the Pipeline', text: 'Choose the right sequence of blocks to repair a degraded image.' },
  { key: 'challenge', icon: '⏱', title: 'Challenge Mode', text: 'Improve a noisy image against the clock. Scored on PSNR, SSIM and time.' },
  { key: 'classroom', icon: '🎓', title: 'Classroom Mode', text: 'Projector mode for juniors: big question, big timer, reveal and explain.' },
]

export function PlayerFields({ name, roll, setName, setRoll }) {
  return (
    <div className="grid-2">
      <label className="field"><span className="field-label">Name (for the leaderboard)</span>
        <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label>
      <label className="field"><span className="field-label">Roll number</span>
        <input type="text" value={roll} onChange={(e) => setRoll(e.target.value)} placeholder="Optional" /></label>
    </div>
  )
}

function QuizSetup({ mode, onStart }) {
  const { call } = useApp()
  const [categories, setCategories] = useState([])
  const [chosen, setChosen] = useState([])
  const [difficulty, setDifficulty] = useState('mixed')
  const [n, setN] = useState(10)
  useEffect(() => {
    call('quizCategories', {}, { quiet: true }).then((c) => c && setCategories(asArray(c)))
  }, [call])
  const toggle = (c) => setChosen((s) => (s.includes(c) ? s.filter((x) => x !== c) : [...s, c]))
  const start = async () => {
    const params = mode === 'kernel' ? { mode: 'kernel', n } : { difficulty, categories: chosen.length ? chosen : 'all', n }
    const qs = await call('quizQuestions', params, { label: 'quizEngine select' })
    if (qs) onStart(asArray(qs))
  }
  return (
    <div className="controls">
      {mode !== 'kernel' && (
        <>
          <span className="field-label">Difficulty</span>
          <Segmented value={difficulty} onChange={setDifficulty} options={[{ value: 'mixed', label: 'Mixed' }, { value: 'easy', label: 'Easy' }, { value: 'medium', label: 'Medium' }, { value: 'hard', label: 'Hard' }]} />
          <span className="field-label">Categories (none selected = all)</span>
          <div className="row">
            {categories.map((c) => (
              <button key={c} className={`btn btn-small ${chosen.includes(c) ? 'btn-navy' : ''}`} onClick={() => toggle(c)}>{c}</button>
            ))}
          </div>
        </>
      )}
      <span className="field-label">Questions</span>
      <Segmented value={n} onChange={setN} options={[5, 10, 15].map((v) => ({ value: v, label: String(v) }))} />
      <button className="btn btn-primary" onClick={start}>Start {mode === 'kernel' ? 'Kernel Quiz' : mode === 'classroom' ? 'Classroom session' : 'Rapid Fire Quiz'}</button>
    </div>
  )
}

function Summary({ summary, progress, onAgain }) {
  return (
    <Card className="quiz-card">
      <div className="big-score">{summary.score}</div>
      <p style={{ textAlign: 'center' }} className="muted">points</p>
      <div className="row" style={{ justifyContent: 'center', gap: 30, margin: '10px 0 16px' }}>
        <div><b>{summary.correct} / {summary.total}</b> correct</div>
        <div><b>{fmt(summary.accuracy, 1)}%</b> accuracy</div>
        <div><b>{summary.bestStreak}</b> best streak</div>
        {progress && <div>Level <b>{progress.level}</b> · {progress.xp} XP</div>}
      </div>
      {progress && asArray(progress.newBadges).length > 0 && <Note kind="ok">🏅 New badge: <b>{asArray(progress.newBadges).join(', ')}</b></Note>}
      {summary.correct === summary.total && summary.total >= 10 && <Note kind="ok">💯 Perfect quiz!</Note>}
      <div className="row" style={{ justifyContent: 'center', marginTop: 14 }}>
        <button className="btn btn-primary" onClick={onAgain}>Play again</button>
        <a className="btn" href="#leaderboard">Leaderboard</a>
        <a className="btn" href="#dashboard">Dashboard</a>
      </div>
    </Card>
  )
}

function TimedQuiz({ mode }) {
  const { call, refreshProgress } = useApp()
  const [questions, setQuestions] = useState(null)
  const [summary, setSummary] = useState(null)
  const [name, setName] = useState('')
  const [roll, setRoll] = useState('')
  const [classScore, setClassScore] = useState(null)

  const finish = async (results) => {
    if (mode === 'classroom') {
      const correct = results.filter((r) => r.correct).length
      setClassScore({ correct, total: results.length })
      setQuestions(null)
      return
    }
    const d = await call('quizSubmit', { results, name, roll, mode: mode === 'kernel' ? 'Kernel Quiz' : 'Rapid Fire' }, { label: 'Scoring quiz' })
    if (d) {
      setSummary(d)
      refreshProgress()
    }
    setQuestions(null)
  }

  if (questions) {
    return (
      <Card>
        <QuizRunner questions={questions} timePerQuestion={10} classroom={mode === 'classroom'} onFinish={finish} onQuit={() => setQuestions(null)} />
      </Card>
    )
  }
  if (summary) return <Summary summary={summary.summary} progress={summary.progress} onAgain={() => setSummary(null)} />
  return (
    <Card title={mode === 'kernel' ? 'Kernel Quiz' : mode === 'classroom' ? 'Classroom Mode' : 'Rapid Fire Quiz'}>
      {classScore && <Note kind="ok">Class result of the last session: <b>{classScore.correct} / {classScore.total}</b> answered correctly.</Note>}
      {mode === 'classroom'
        ? <p className="small">Put this on the projector. The question and a 10-second timer are shown in large type. Click the option the class chooses (or let the timer run out / "Reveal answer now"), then discuss the explanation.</p>
        : <PlayerFields name={name} roll={roll} setName={setName} setRoll={setRoll} />}
      <div style={{ marginTop: 12 }}>
        <QuizSetup mode={mode} onStart={(qs) => { setClassScore(null); setQuestions(qs) }} />
      </div>
      <p className="small muted" style={{ marginTop: 12 }}>
        Scoring (quizEngine.m): 100 × difficulty (easy 1, medium 1.5, hard 2) + 5 per second left + 10 × streak bonus.
      </p>
    </Card>
  )
}

export default function QuizHub() {
  const [game, setGame] = useState(null)
  const current = GAMES.find((g) => g.key === game)
  return (
    <Page title={current ? current.title : 'Arcade'} eyebrow="Play" subtitle={current ? current.text : 'Six ways to test yourself. Questions, images and scores all come from MATLAB.'}
      actions={game && <button className="btn" onClick={() => setGame(null)}>← All games</button>}>
      {!game && (
        <div className="game-tiles">
          {GAMES.map((g) => (
            <button key={g.key} className="game-tile" onClick={() => setGame(g.key)}>
              <span className="ic">{g.icon}</span><b>{g.title}</b><span>{g.text}</span>
            </button>
          ))}
        </div>
      )}
      {(game === 'rapid' || game === 'kernel' || game === 'classroom') && <TimedQuiz key={game} mode={game} />}
      {game === 'guess' && <GuessFilter />}
      {game === 'pipeline' && <PipelineGame />}
      {game === 'challenge' && <ChallengeMode />}
    </Page>
  )
}
