function P = pipelineProblems()
%PIPELINEPROBLEMS Problems for the "Build the Pipeline" game.
%   Each problem degrades a clean image in a known way; the student must
%   choose the right sequence of processing blocks to repair it.
%
%   degrade  : cell array of {operation, parameter} applied to the clean image
%   expected : the ideal block sequence
%   accepted : other sequences that also earn full marks

P = struct('id', {}, 'title', {}, 'description', {}, 'degrade', {}, ...
    'expected', {}, 'accepted', {}, 'explanation', {});

P(end+1) = struct('id', 'sp', 'title', 'Remove salt-and-pepper noise', ...
    'description', 'The image is corrupted by impulse (salt & pepper) noise. Remove it while keeping edges sharp.', ...
    'degrade', {{{'saltpepper', 0.08}}}, ...
    'expected', {{'median'}}, 'accepted', {{{'median', 'median'}}}, ...
    'explanation', 'Impulses are extreme values; the median ignores them. A mean filter would only smear them.');

P(end+1) = struct('id', 'spcontrast', 'title', 'Remove noise and improve contrast', ...
    'description', 'The image is dull (low contrast) AND has salt & pepper noise.', ...
    'degrade', {{{'contrast', 0.35}, {'saltpepper', 0.05}}}, ...
    'expected', {{'median', 'clahe'}}, 'accepted', {{{'median', 'histeq'}}}, ...
    'explanation', 'Remove the impulses FIRST (median), then enhance contrast. Equalising first would also stretch the noise.');

P(end+1) = struct('id', 'gauss', 'title', 'Reduce Gaussian sensor noise', ...
    'description', 'The image has fine grainy Gaussian noise all over.', ...
    'degrade', {{{'gaussian', 0.01}}}, ...
    'expected', {{'gaussian'}}, 'accepted', {{{'mean'}}}, ...
    'explanation', 'Gaussian noise is zero-mean and affects every pixel - averaging (Gaussian or mean filter) cancels it out.');

P(end+1) = struct('id', 'blur', 'title', 'Sharpen a blurred image', ...
    'description', 'The image is slightly out of focus. Make the details crisper.', ...
    'degrade', {{{'blur', 1.5}}}, ...
    'expected', {{'unsharp'}}, 'accepted', {{{'laplacian'}}}, ...
    'explanation', 'Blur removes high-frequency detail; sharpening (unsharp masking or Laplacian) adds it back.');

P(end+1) = struct('id', 'dark', 'title', 'Fix a dark, low-contrast image', ...
    'description', 'The image is too dark and the histogram is squeezed into the low grey levels.', ...
    'degrade', {{{'dark', 0.4}}}, ...
    'expected', {{'histeq'}}, 'accepted', {{{'clahe'}, {'gamma'}}}, ...
    'explanation', 'Histogram equalisation (or CLAHE / gamma < 1) spreads the dark grey levels over the full range.');

P(end+1) = struct('id', 'noisysharp', 'title', 'Denoise, then sharpen', ...
    'description', 'The image is blurred AND has Gaussian noise. Recover detail without amplifying noise.', ...
    'degrade', {{{'blur', 1.2}, {'gaussian', 0.004}}}, ...
    'expected', {{'gaussian', 'unsharp'}}, 'accepted', {{{'median', 'unsharp'}, {'gaussian', 'laplacian'}}}, ...
    'explanation', 'Sharpening amplifies noise, so smooth first and sharpen second.');
end
