function Q = questionBank()
%QUESTIONBANK All ImageLab quiz questions.
%   Each question has:
%     id, category, difficulty (easy|medium|hard), type
%     (mcq | truefalse | kernel | filter | output | numerical | conceptual),
%     question, options (cell), answer (1-based index into options),
%     explanation, kernel (matrix shown with the question, or []).

Q = struct('id', {}, 'category', {}, 'difficulty', {}, 'type', {}, ...
    'question', {}, 'options', {}, 'answer', {}, 'explanation', {}, 'kernel', {});

% ------------------------------------------------------------ Fundamentals
Q = add(Q, 'FUN1', 'Fundamentals', 'easy', 'mcq', ...
    'A digital image is best described as:', ...
    {'A continuous function f(x,y)', 'A 2-D array of sampled and quantised values', 'A frequency spectrum', 'A set of vectors'}, 2, ...
    'Digitisation = sampling (choosing the pixel grid) + quantisation (choosing a finite set of grey levels), giving a matrix.');
Q = add(Q, 'FUN2', 'Fundamentals', 'easy', 'numerical', ...
    'How many grey levels can an 8-bit image represent?', ...
    {'8', '128', '256', '1024'}, 3, '2^8 = 256 levels: 0 (black) to 255 (white).');
Q = add(Q, 'FUN3', 'Fundamentals', 'medium', 'numerical', ...
    'What is the city-block (D4) distance between pixels (2,3) and (5,7)?', ...
    {'5', '7', '4', '3.5'}, 2, 'D4 = |2-5| + |3-7| = 3 + 4 = 7.');
Q = add(Q, 'FUN4', 'Fundamentals', 'medium', 'numerical', ...
    'What is the chessboard (D8) distance between pixels (2,3) and (5,7)?', ...
    {'4', '5', '7', '3'}, 1, 'D8 = max(|2-5|, |3-7|) = max(3,4) = 4.');
Q = add(Q, 'FUN5', 'Fundamentals', 'easy', 'mcq', ...
    'How many pixels are in the 8-neighbourhood N8(p) of an interior pixel?', ...
    {'4', '8', '9', '6'}, 2, 'N8(p) = the 4 horizontal/vertical neighbours N4(p) plus the 4 diagonal neighbours ND(p).');
Q = add(Q, 'FUN6', 'Fundamentals', 'hard', 'conceptual', ...
    'Why was m-adjacency (mixed adjacency) introduced?', ...
    {'To make images smaller', 'To remove the ambiguous multiple paths of 8-adjacency', 'To speed up convolution', 'To define colour neighbours'}, 2, ...
    'With 8-adjacency two pixels can be connected by more than one path; m-adjacency only allows a diagonal link when no 4-path exists.');
Q = add(Q, 'FUN7', 'Fundamentals', 'medium', 'truefalse', ...
    'Reducing the number of grey levels too much can cause false contouring.', ...
    {'True', 'False'}, 1, 'Too few quantisation levels turn smooth gradients into visible bands (false contours).');
Q = add(Q, 'FUN8', 'Fundamentals', 'medium', 'mcq', ...
    'The visible spectrum spans approximately:', ...
    {'0.01 - 10 nm', '400 - 700 nm', '1 - 10 mm', '10 - 100 m'}, 2, ...
    'Visible light is roughly 400 nm (violet) to 700 nm (red) in the electromagnetic spectrum.');
Q = add(Q, 'FUN9', 'Fundamentals', 'hard', 'conceptual', ...
    'Mach bands and simultaneous contrast show that:', ...
    {'Perceived brightness is not a simple function of intensity', 'The eye sees only 16 grey levels', 'Cones detect brightness only', 'Images must be sharpened'}, 1, ...
    'The visual system enhances edges and judges brightness relative to the surroundings, so perceived brightness differs from the physical intensity.');
Q = add(Q, 'FUN10', 'Fundamentals', 'easy', 'mcq', ...
    'Which MATLAB function reads an image file?', ...
    {'imshow', 'imread', 'imwrite', 'load'}, 2, 'imread reads the image into a matrix; imshow displays it; imwrite saves it.');
Q = add(Q, 'FUN11', 'Fundamentals', 'medium', 'mcq', ...
    'Which receptors in the retina are responsible for colour vision in bright light?', ...
    {'Rods', 'Cones', 'Ganglion cells', 'Lens fibres'}, 2, ...
    'Cones (6-7 million, concentrated in the fovea) give photopic colour vision; rods give scotopic low-light vision.');

% --------------------------------------------------------------- Histogram
Q = add(Q, 'HIS1', 'Histogram', 'easy', 'mcq', ...
    'An image whose histogram is concentrated in a narrow band has:', ...
    {'High contrast', 'Low contrast', 'Salt & pepper noise', 'Many edges'}, 2, 'A narrow histogram means only a few grey levels are used, i.e. low contrast.');
Q = add(Q, 'HIS2', 'Histogram', 'medium', 'mcq', ...
    'Histogram equalisation maps grey level r_k using:', ...
    {'The PDF', 'The scaled cumulative distribution function (CDF)', 'The mean', 'A Gaussian'}, 2, 's_k = (L-1) * sum_{j<=k} p(r_j): the scaled CDF.');
Q = add(Q, 'HIS3', 'Histogram', 'medium', 'mcq', ...
    'What does CLAHE add to adaptive histogram equalisation?', ...
    {'Colour conversion', 'A clip limit that limits contrast amplification', 'Frequency filtering', 'Edge detection'}, 2, ...
    'CLAHE clips each tile histogram so noise in flat regions is not over-amplified, then interpolates between tiles.');
Q = add(Q, 'HIS4', 'Histogram', 'easy', 'truefalse', ...
    'Gamma correction with gamma < 1 brightens dark regions.', {'True', 'False'}, 1, ...
    's = r^gamma with gamma < 1 lifts small values (e.g. 0.25^0.5 = 0.5).');
Q = add(Q, 'HIS5', 'Histogram', 'medium', 'numerical', ...
    'A 4-pixel image has levels [0 0 1 3] (L = 4). What is the CDF value at r = 1?', ...
    {'0.25', '0.5', '0.75', '1'}, 3, 'p(0) = 2/4, p(1) = 1/4, so CDF(1) = 0.75.');
Q = add(Q, 'HIS6', 'Histogram', 'easy', 'mcq', ...
    'Which MATLAB function performs histogram equalisation?', {'imhist', 'histeq', 'imadjust', 'adapthisteq'}, 2, ...
    'histeq = global equalisation; adapthisteq = CLAHE; imadjust = contrast stretching; imhist = compute histogram.');
Q = add(Q, 'HIS7', 'Histogram', 'hard', 'conceptual', ...
    'Why is the equalised histogram of a digital image usually NOT perfectly flat?', ...
    {'Because of rounding errors in MATLAB', 'Because pixels with the same level are all mapped to the same new level', 'Because the CDF is not monotonic', 'Because the mean changes'}, 2, ...
    'The mapping is a function of grey level: all pixels of one level move together, so bins can be merged or left empty but never split.');
Q = add(Q, 'HIS8', 'Histogram', 'medium', 'mcq', ...
    'The log transformation s = c log(1 + r) is mainly used to:', ...
    {'Compress a large dynamic range', 'Remove noise', 'Detect edges', 'Binarise an image'}, 1, ...
    'It expands dark values and compresses bright ones - ideal for displaying images with a huge range of values.');
Q = add(Q, 'HIS9', 'Histogram', 'hard', 'numerical', ...
    'An image with all 256 grey levels equally likely has entropy:', {'1 bit', '4 bits', '8 bits', '256 bits'}, 3, ...
    'H = -sum p log2 p = -256 * (1/256) log2(1/256) = 8 bits.');

% --------------------------------------------------------- Spatial Filters
Q = add(Q, 'SPA1', 'Spatial Filters', 'easy', 'mcq', ...
    'Spatial-domain processing operates directly on:', {'The Fourier transform', 'The image pixels', 'The histogram only', 'The colour map'}, 2, ...
    'Spatial domain = the image plane itself: g(x,y) = T[f(x,y)] using a pixel and its neighbourhood.');
Q = add(Q, 'SPA2', 'Spatial Filters', 'medium', 'mcq', ...
    'Why are spatial filter kernels usually of odd size (3x3, 5x5)?', ...
    {'They are faster', 'They have a well-defined centre pixel', 'MATLAB requires it', 'Even kernels cannot be stored'}, 2, ...
    'An odd-sized kernel is symmetric around its centre, so the output is aligned with the input pixel.');
Q = add(Q, 'SPA3', 'Spatial Filters', 'medium', 'mcq', ...
    'What happens at the image border during filtering if padding is "replicate"?', ...
    {'Outside pixels are 0', 'Outside pixels copy the nearest border pixel', 'The border is cropped', 'The kernel is flipped'}, 2, ...
    'Replicate padding repeats the edge pixel, avoiding the dark frame that zero padding produces.');
Q = add(Q, 'SPA4', 'Spatial Filters', 'easy', 'truefalse', ...
    'Increasing the size of a mean filter increases the blurring.', {'True', 'False'}, 1, ...
    'A larger window averages over more pixels, removing more detail.');
Q = add(Q, 'SPA5', 'Spatial Filters', 'hard', 'mcq', ...
    'A kernel whose coefficients sum to 0 will produce, in a flat (constant) region:', ...
    {'The original value', '0', '1', 'The maximum'}, 2, ...
    'Sum of products = constant * sum(weights) = 0: derivative kernels respond only to changes.');

% ---------------------------------------------------------- Linear Filters
Q = add(Q, 'LIN1', 'Linear Filters', 'easy', 'kernel', ...
    'Identify this kernel:', {'Mean (box) filter', 'Laplacian', 'Sobel X', 'Gaussian'}, 1, ...
    'All nine weights are equal (1/9): the arithmetic mean filter.', ones(3) / 9);
Q = add(Q, 'LIN2', 'Linear Filters', 'medium', 'kernel', ...
    'Identify this kernel:', {'Mean', 'Weighted mean (Gaussian-like)', 'Laplacian', 'Prewitt'}, 2, ...
    'Larger weights in the centre falling off with distance: a weighted average / binomial approximation of the Gaussian.', [1 2 1; 2 4 2; 1 2 1] / 16);
Q = add(Q, 'LIN3', 'Linear Filters', 'medium', 'mcq', ...
    'Which property defines a LINEAR filter?', ...
    {'It sorts the neighbourhood', 'Its output is a weighted sum of the neighbourhood (superposition holds)', 'It works only on binary images', 'It uses the median'}, 2, ...
    'Linear: T[a f + b g] = a T[f] + b T[g]. Every linear spatial filter is a sum of products with a kernel.');
Q = add(Q, 'LIN4', 'Linear Filters', 'medium', 'mcq', ...
    'In a Gaussian filter, increasing sigma:', {'Reduces blurring', 'Increases blurring', 'Detects edges', 'Has no effect'}, 2, ...
    'A larger sigma spreads the weights over more neighbours, so the image is smoothed more.');
Q = add(Q, 'LIN5', 'Linear Filters', 'easy', 'numerical', ...
    'Apply a 3x3 mean filter to the centre of [1 2 3; 4 5 6; 7 8 9]. Result?', {'4', '5', '6', '45'}, 2, ...
    '(1+2+...+9)/9 = 45/9 = 5.');
Q = add(Q, 'LIN6', 'Linear Filters', 'hard', 'conceptual', ...
    'Why does the mean filter perform badly on salt & pepper noise?', ...
    {'It cannot be computed at borders', 'It spreads the extreme impulse value over the neighbourhood instead of removing it', 'It sharpens the noise', 'It changes colours'}, 2, ...
    'An impulse of 255 among values of ~100 raises the average of every window that contains it - the noise is smeared, not removed.');
Q = add(Q, 'LIN7', 'Linear Filters', 'medium', 'mcq', ...
    'Which MATLAB call creates a 5x5 Gaussian kernel with sigma = 1?', ...
    {'fspecial(''average'',5)', 'fspecial(''gaussian'',5,1)', 'imgaussfilt(5)', 'gauss(5,1)'}, 2, 'fspecial(''gaussian'', hsize, sigma) returns the normalised kernel.');

% ------------------------------------------------------ Non-Linear Filters
Q = add(Q, 'NON1', 'Non-Linear Filters', 'easy', 'mcq', ...
    'Which filter is best suited for salt-and-pepper noise?', {'Mean', 'Median', 'Laplacian', 'Sobel'}, 2, ...
    'Impulses are extreme values; after sorting they land at the ends of the list and the median ignores them.');
Q = add(Q, 'NON2', 'Non-Linear Filters', 'easy', 'numerical', ...
    'What is the median of the window [10 200 12; 11 0 13; 9 14 255]?', {'12', '13', '11', '58'}, 1, ...
    'Sorted: 0 9 10 11 12 13 14 200 255 -> 5th value = 12. The impulses 0, 200, 255 are ignored.');
Q = add(Q, 'NON3', 'Non-Linear Filters', 'medium', 'mcq', ...
    'In ordfilt2(I, 1, true(3)), which filter is applied?', {'Median', 'Maximum', 'Minimum', 'Mean'}, 3, ...
    'Rank 1 of the sorted 3x3 window = the smallest value = minimum filter.');
Q = add(Q, 'NON4', 'Non-Linear Filters', 'medium', 'mcq', ...
    'The maximum filter is most useful for removing:', {'Pepper (black) noise', 'Salt (white) noise', 'Gaussian noise', 'Blur'}, 1, ...
    'Taking the maximum discards dark impulses; salt (white) noise would instead be enlarged.');
Q = add(Q, 'NON5', 'Non-Linear Filters', 'hard', 'mcq', ...
    'For a 5x5 window, which rank gives the median?', {'12', '13', '25', '5'}, 2, 'N = 25 values, median = ceil(25/2) = 13th smallest.');
Q = add(Q, 'NON6', 'Non-Linear Filters', 'medium', 'mcq', ...
    'The midpoint filter computes:', {'(min + max)/2', 'median', 'mean of the middle 50%', 'max - min'}, 1, ...
    'Midpoint = average of the minimum and maximum in the window; good for uniform / Gaussian noise.');
Q = add(Q, 'NON7', 'Non-Linear Filters', 'hard', 'truefalse', ...
    'The median filter is a linear filter because it uses a sliding window.', {'True', 'False'}, 2, ...
    'False. median(f + g) ~= median(f) + median(g) - sorting is a non-linear operation.');
Q = add(Q, 'NON8', 'Non-Linear Filters', 'medium', 'conceptual', ...
    'Why does the median filter preserve edges better than the mean filter?', ...
    {'It uses a larger window', 'It outputs an existing neighbourhood value rather than creating intermediate values', 'It works in the frequency domain', 'It sharpens edges'}, 2, ...
    'At an edge, more than half the window lies on one side, so the median picks a value from that side and the edge stays sharp.');

% ------------------------------------------------------------------ Noise
Q = add(Q, 'NOI1', 'Noise', 'easy', 'mcq', ...
    'Which noise model sets random pixels to 0 or 255?', {'Gaussian', 'Salt & pepper', 'Speckle', 'Poisson'}, 2, 'Impulse (salt & pepper) noise replaces pixels with the extreme values.');
Q = add(Q, 'NOI2', 'Noise', 'medium', 'mcq', ...
    'Speckle noise is:', {'Additive', 'Multiplicative', 'Impulse', 'Periodic'}, 2, 'Speckle: g = f + n*f - its strength depends on the signal (ultrasound, radar).');
Q = add(Q, 'NOI3', 'Noise', 'medium', 'mcq', ...
    'Poisson (shot) noise has the property that:', {'Variance equals the mean', 'It is always zero-mean', 'It affects only edges', 'It is periodic'}, 1, ...
    'Photon counting follows a Poisson distribution, whose variance equals its mean - brighter pixels are noisier in absolute terms.');
Q = add(Q, 'NOI4', 'Noise', 'easy', 'mcq', ...
    'Which MATLAB call adds Gaussian noise with variance 0.01?', ...
    {'imnoise(I,''gaussian'',0,0.01)', 'imnoise(I,0.01)', 'randn(I,0.01)', 'noise(I,''g'')'}, 1, 'imnoise(I, ''gaussian'', mean, variance).');
Q = add(Q, 'NOI5', 'Noise', 'medium', 'numerical', ...
    'If the MSE between two [0,1] images is 0.01, what is the PSNR?', {'10 dB', '20 dB', '40 dB', '100 dB'}, 2, ...
    'PSNR = 10 log10(1 / 0.01) = 10 * 2 = 20 dB.');
Q = add(Q, 'NOI6', 'Noise', 'hard', 'mcq', ...
    'A degradation model is written g(x,y) = h(x,y) * f(x,y) + eta(x,y). What is h?', ...
    {'The noise', 'The degradation (point-spread) function', 'The restored image', 'The histogram'}, 2, ...
    'h is the linear, position-invariant degradation (e.g. blur) and eta is additive noise.');
Q = add(Q, 'NOI7', 'Noise', 'medium', 'mcq', ...
    'Which metric compares luminance, contrast and structure?', {'MSE', 'PSNR', 'SSIM', 'Entropy'}, 3, 'SSIM (structural similarity) is closer to human perception than MSE/PSNR.');
Q = add(Q, 'NOI8', 'Noise', 'hard', 'mcq', ...
    'Which restoration filter is best for a MIX of Gaussian and impulse noise?', {'Mean', 'Alpha-trimmed mean', 'Max', 'Laplacian'}, 2, ...
    'Alpha-trimmed mean drops the d/2 smallest and largest values (impulses) and averages the rest (Gaussian).');

% ------------------------------------------------------------ Correlation
Q = add(Q, 'COR1', 'Correlation', 'easy', 'mcq', ...
    'In spatial correlation the kernel is:', {'Flipped by 180 degrees', 'Not flipped', 'Transposed', 'Inverted'}, 2, ...
    'Correlation slides the kernel as it is; convolution first rotates it by 180 degrees.');
Q = add(Q, 'COR2', 'Correlation', 'medium', 'numerical', ...
    'Correlate [1 2 3; 4 5 6; 7 8 9] with [1 0 -1; 1 0 -1; 1 0 -1] at the centre. Result?', {'6', '-6', '0', '18'}, 2, ...
    '(1+4+7) - (3+6+9) = 12 - 18 = -6.');
Q = add(Q, 'COR3', 'Correlation', 'medium', 'mcq', ...
    'Correlating an image with a discrete unit impulse gives:', {'The kernel', 'A rotated (180 degree) copy of the kernel', 'Zero', 'The image'}, 2, ...
    'Correlation with an impulse produces the kernel rotated by 180 degrees; convolution reproduces the kernel itself.');
Q = add(Q, 'COR4', 'Correlation', 'hard', 'mcq', ...
    'Correlation is commonly used for:', {'Template matching', 'Histogram equalisation', 'Colour conversion', 'Quantisation'}, 1, ...
    'The correlation output is largest where the image looks most like the kernel (template).');
Q = add(Q, 'COR5', 'Correlation', 'easy', 'truefalse', ...
    'imfilter performs correlation by default.', {'True', 'False'}, 1, 'imfilter(I,h) uses ''corr'' unless ''conv'' is specified.');

% ------------------------------------------------------------ Convolution
Q = add(Q, 'CON1', 'Convolution', 'easy', 'mcq', ...
    'Convolution differs from correlation because the kernel is:', {'Normalised', 'Rotated by 180 degrees', 'Squared', 'Transposed'}, 2, ...
    'Flip horizontally and vertically (rot90(K,2)), then proceed exactly like correlation.');
Q = add(Q, 'CON2', 'Convolution', 'medium', 'truefalse', ...
    'For a symmetric kernel such as the Gaussian, correlation and convolution give the same result.', {'True', 'False'}, 1, ...
    'Rotating a symmetric kernel by 180 degrees does not change it.');
Q = add(Q, 'CON3', 'Convolution', 'medium', 'mcq', ...
    'What is rot90([1 2; 3 4], 2)?', {'[4 3; 2 1]', '[1 3; 2 4]', '[3 4; 1 2]', '[2 1; 4 3]'}, 1, 'A 180 degree rotation reverses both row and column order.');
Q = add(Q, 'CON4', 'Convolution', 'hard', 'mcq', ...
    'Size of conv2(A, B, ''full'') for A 5x5 and B 3x3?', {'5x5', '3x3', '7x7', '8x8'}, 3, 'Full output: (5+3-1) x (5+3-1) = 7x7.');
Q = add(Q, 'CON5', 'Convolution', 'hard', 'conceptual', ...
    'Which property does convolution have that correlation lacks?', {'Linearity', 'Commutativity (f*g = g*f)', 'Shift invariance', 'Speed'}, 2, ...
    'Both are linear and shift-invariant, but only convolution is commutative and associative, so filters can be combined into one kernel.');
Q = add(Q, 'CON6', 'Convolution', 'medium', 'mcq', ...
    'Which base MATLAB function performs 2-D convolution?', {'conv2', 'corr2', 'histeq', 'imadjust'}, 1, ...
    'conv2 convolves two matrices; corr2 returns a single correlation COEFFICIENT, not a filtered image.');

% ------------------------------------------------------------- Sharpening
Q = add(Q, 'SHA1', 'Sharpening', 'easy', 'kernel', ...
    'Identify this kernel:', {'Mean', 'Laplacian', 'Sobel Y', 'Identity'}, 2, ...
    'Centre -4 and the four neighbours 1: the 4-neighbour Laplacian (second derivative).', [0 1 0; 1 -4 1; 0 1 0]);
Q = add(Q, 'SHA2', 'Sharpening', 'medium', 'mcq', ...
    'With a Laplacian kernel whose centre is NEGATIVE, sharpening is:', {'g = f + lap(f)', 'g = f - lap(f)', 'g = lap(f)', 'g = f * lap(f)'}, 2, ...
    'Subtract the Laplacian when the centre coefficient is negative (add it if the centre is positive).');
Q = add(Q, 'SHA3', 'Sharpening', 'medium', 'mcq', ...
    'Unsharp masking computes:', {'f + k (f - blur(f))', 'blur(f) - f', 'f * f', 'median(f)'}, 1, ...
    'mask = f - blurred; g = f + k*mask. k = 1: unsharp masking, k > 1: high-boost.');
Q = add(Q, 'SHA4', 'Sharpening', 'hard', 'kernel', ...
    'Identify this kernel:', {'Laplacian', 'Sharpening (identity - Laplacian)', 'Mean', 'Emboss'}, 2, ...
    'Centre 5, neighbours -1: identity [0 0 0;0 1 0;0 0 0] minus the Laplacian -> sharpening in one pass.', [0 -1 0; -1 5 -1; 0 -1 0]);
Q = add(Q, 'SHA5', 'Sharpening', 'medium', 'truefalse', ...
    'Sharpening also amplifies noise.', {'True', 'False'}, 1, 'Derivatives respond to every rapid change, including noise; smoothing first helps.');
Q = add(Q, 'SHA6', 'Sharpening', 'hard', 'mcq', ...
    'In high-boost filtering g = f + k * mask, the case k > 1 means:', {'Less sharpening', 'The detail (mask) is amplified more strongly', 'The image is blurred', 'The image is inverted'}, 2, ...
    'k > 1 emphasises the high-frequency detail more than standard unsharp masking (k = 1).');

% --------------------------------------------------------- Edge Detection
Q = add(Q, 'EDG1', 'Edge Detection', 'easy', 'kernel', ...
    'Identify this kernel:', {'Mean', 'Sobel X', 'Prewitt Y', 'Laplacian'}, 2, ...
    'Columns -1/0/+1 with weights 1-2-1: Sobel X, the horizontal derivative (detects vertical edges).', [-1 0 1; -2 0 2; -1 0 1]);
Q = add(Q, 'EDG2', 'Edge Detection', 'medium', 'kernel', ...
    'Identify this kernel:', {'Sobel X', 'Prewitt X', 'Prewitt Y', 'Roberts'}, 3, ...
    'Rows -1/0/+1 with equal weights: Prewitt Y (vertical derivative, horizontal edges).', [-1 -1 -1; 0 0 0; 1 1 1]);
Q = add(Q, 'EDG3', 'Edge Detection', 'medium', 'mcq', ...
    'Which detector uses non-maximum suppression and hysteresis thresholding?', {'Roberts', 'Sobel', 'Canny', 'Prewitt'}, 3, ...
    'Canny: Gaussian smoothing, gradient, non-maximum suppression (thin edges), double threshold + hysteresis (edge linking).');
Q = add(Q, 'EDG4', 'Edge Detection', 'easy', 'mcq', ...
    'The gradient magnitude is:', {'gx + gy', 'sqrt(gx^2 + gy^2)', 'gx * gy', 'max(gx)'}, 2, 'Edge strength |grad f| = sqrt(gx^2 + gy^2) (approximated by |gx|+|gy|).');
Q = add(Q, 'EDG5', 'Edge Detection', 'hard', 'mcq', ...
    'Edges in the LoG (Marr-Hildreth) method are located at:', {'Maxima of the response', 'Zero crossings of the response', 'Pixels above the mean', 'Corners'}, 2, ...
    'The second derivative changes sign across an edge, so edges are the zero crossings.');
Q = add(Q, 'EDG6', 'Edge Detection', 'medium', 'mcq', ...
    'Compared with Prewitt, the Sobel operator:', {'Has no smoothing', 'Gives more weight to the centre row/column, adding smoothing', 'Is a second-derivative operator', 'Uses 2x2 kernels'}, 2, ...
    'The 1-2-1 weights act as a small smoothing filter perpendicular to the derivative.');
Q = add(Q, 'EDG7', 'Edge Detection', 'medium', 'mcq', ...
    'The Roberts operator uses kernels of size:', {'2x2', '3x3', '5x5', '1x3'}, 1, 'Roberts cross: two 2x2 diagonal difference kernels.');
Q = add(Q, 'EDG8', 'Edge Detection', 'easy', 'mcq', ...
    'What is an edge?', {'A pixel with value 255', 'A place where intensity changes abruptly', 'The image border', 'A noise pixel'}, 2, ...
    'Edges are boundaries between regions with significantly different intensities (large first derivative).');

% ----------------------------------------------------------- Segmentation
Q = add(Q, 'SEG1', 'Segmentation', 'easy', 'mcq', ...
    'Otsu''s method selects the threshold that maximises:', {'Within-class variance', 'Between-class variance', 'Entropy', 'The mean'}, 2, ...
    'Maximising between-class variance = minimising within-class variance: the best separation of the two classes.');
Q = add(Q, 'SEG2', 'Segmentation', 'medium', 'mcq', ...
    'When is ADAPTIVE thresholding preferred?', {'Uniform illumination', 'Uneven illumination', 'Binary images', 'Colour images only'}, 2, ...
    'With a lighting gradient no single threshold works; a local threshold follows the illumination.');
Q = add(Q, 'SEG3', 'Segmentation', 'medium', 'kernel', ...
    'Identify this mask:', {'Point detection', 'Mean', 'Horizontal line detection', 'Sobel'}, 1, ...
    'Centre 8, all neighbours -1: responds strongly to an isolated point (sums to zero).', [-1 -1 -1; -1 8 -1; -1 -1 -1]);
Q = add(Q, 'SEG4', 'Segmentation', 'hard', 'kernel', ...
    'This mask detects lines in which direction?', {'Vertical', 'Horizontal', '+45 degrees', '-45 degrees'}, 2, ...
    'The middle ROW has weight 2: it responds to 1-pixel-thick horizontal lines.', [-1 -1 -1; 2 2 2; -1 -1 -1]);
Q = add(Q, 'SEG5', 'Segmentation', 'medium', 'mcq', ...
    'Region growing starts from:', {'The image border', 'Seed points', 'The histogram', 'Edge pixels only'}, 2, ...
    'Neighbours similar to the seed (within a tolerance) are added until no more pixels qualify.');
Q = add(Q, 'SEG6', 'Segmentation', 'hard', 'mcq', ...
    'Region splitting and merging typically uses which data structure?', {'Stack of histograms', 'Quadtree', 'Linked list of edges', 'Hash table'}, 2, ...
    'Non-homogeneous regions are split into four quadrants recursively (quadtree), then similar neighbours are merged.');
Q = add(Q, 'SEG7', 'Segmentation', 'easy', 'mcq', ...
    'Which MATLAB function labels connected components?', {'bwlabel', 'imhist', 'edge', 'fspecial'}, 1, ...
    'bwlabel assigns a number to each connected region; regionprops then measures area, centroid, etc.');
Q = add(Q, 'SEG8', 'Segmentation', 'medium', 'mcq', ...
    'Edge linking is needed because:', {'Edge detectors produce broken, discontinuous edges', 'Edges are too thick', 'Thresholds are global', 'Images are coloured'}, 1, ...
    'Noise and uneven lighting break edges; linking (e.g. Canny hysteresis) joins edge pixels into boundaries.');

% ------------------------------------------------------- Color Processing
Q = add(Q, 'COL1', 'Color Processing', 'easy', 'mcq', ...
    'In the HSV model, which channel represents the colour type?', {'Hue', 'Saturation', 'Value', 'Luma'}, 1, 'Hue = colour angle (red, green, ...); Saturation = purity; Value = brightness.');
Q = add(Q, 'COL2', 'Color Processing', 'medium', 'mcq', ...
    'To equalise a colour image without changing its hues, equalise:', {'R, G and B separately', 'Only the V (or Y / L) channel', 'Only the hue', 'The saturation'}, 2, ...
    'Equalising R, G, B independently changes their ratios and shifts colours; equalising brightness keeps them.');
Q = add(Q, 'COL3', 'Color Processing', 'medium', 'mcq', ...
    'In YCbCr, the Y channel carries:', {'Blue difference', 'Luminance (brightness)', 'Red difference', 'Hue'}, 2, 'Y = luma; Cb, Cr = colour differences. Used in JPEG/video.');
Q = add(Q, 'COL4', 'Color Processing', 'hard', 'mcq', ...
    'Which colour space is designed to be approximately perceptually uniform?', {'RGB', 'CMY', 'CIE L*a*b*', 'HSV'}, 3, ...
    'In Lab, equal distances correspond to roughly equal perceived colour differences.');
Q = add(Q, 'COL5', 'Color Processing', 'easy', 'truefalse', ...
    'RGB is an additive colour model.', {'True', 'False'}, 1, 'Red, green and blue light are added; CMY(K) is subtractive.');
Q = add(Q, 'COL6', 'Color Processing', 'medium', 'mcq', ...
    'Multiplying the S channel of an HSV image by 1.5 will:', {'Make colours more vivid', 'Brighten the image', 'Rotate hues', 'Convert to grayscale'}, 1, 'Higher saturation = purer, more vivid colours.');

% -------------------------------------------- Identify the output (images)
Q = add(Q, 'OUT1', 'Spatial Filters', 'medium', 'output', ...
    'An image with salt & pepper noise is filtered. The output is clean and edges are sharp. Which filter was used?', ...
    {'3x3 mean', '3x3 median', 'Laplacian', 'Sobel'}, 2, 'Clean impulses + sharp edges is the signature of the median filter.');
Q = add(Q, 'OUT2', 'Edge Detection', 'medium', 'output', ...
    'The output is mostly black with bright thin lines where objects meet. Which operation produced it?', ...
    {'Gaussian blur', 'Histogram equalisation', 'Edge detection (gradient magnitude)', 'Median filter'}, 3, 'Only intensity changes survive: an edge / gradient image.');
Q = add(Q, 'OUT3', 'Histogram', 'medium', 'output', ...
    'A dull, greyish photo becomes high-contrast and its histogram now covers 0..255. Which operation?', ...
    {'Histogram equalisation', 'Mean filter', 'Min filter', 'Quantisation to 1 bit'}, 1, 'Equalisation spreads the grey levels over the full range.');
end

function Q = add(Q, id, category, difficulty, type, question, options, answer, explanation, kernel)
if nargin < 10, kernel = []; end
Q(end+1) = struct('id', id, 'category', category, 'difficulty', difficulty, ...
    'type', type, 'question', question, 'options', {options}, 'answer', answer, ...
    'explanation', explanation, 'kernel', kernel);
end
